# Use OpenJDK 17
FROM openjdk:17-jdk-slim
# Set the working directory inside the container
WORKDIR /app
# Copy the JAR file generated by Maven to the container and rename it to a fixed name
COPY target/*.jar /app/DocuMan.jar
# Expose the port used by Spring Boot
EXPOSE 8080
# Command to run the Spring Boot app
ENTRYPOINT ["java", "-jar", "DocuMan.jar"]