version: '3.8'

services:
  documan:
    build: .
    ports:
      - "8080:8080"
    networks:
      - documan-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/app/logs

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - documan-network
    restart: unless-stopped

networks:
  documan-network:
    driver: bridge
