spring:
datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password:
h2:
  console:
    enabled: true
jpa:
  hibernate:
    ddl-auto: update

# spring:
#   datasource:
#     url: jdbc:postgresql://db:5432/documandb
#     username: documanuser
#     password: password
#   jpa:
#     hibernate:
#       ddl-auto: update